name: 01-Download-Quran-Kuddari-Fixed
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install git and zip
        run: sudo apt-get update && sudo apt-get install -y git zip

      - name: Clone repository
        run: |
          git clone https://github.com/Kuddari/Quran_analysis_with_python.git Quran_Kuddari_Dataset
          cd Quran_Kuddari_Dataset
          # نمایش لیست فایل‌ها برای اطمینان (اختیاری)
          ls -la

      - name: Compress folder
        run: zip -r "Quran_Kuddari_Dataset.zip" "Quran_Kuddari_Dataset"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "01-Quran-Database-Kuddari"
          path: "Quran_Kuddari_Dataset.zip"
